<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-26 02:43
=======
# Generated by Django 3.2.16 on 2022-10-28 12:21
>>>>>>> 5b4bdfc7f47bc7933ff73f8b9c316895d66d24e3

import app.models
=======

import app.models

>>>>>>> dev2
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=16)),
                ('font', models.CharField(max_length=24)),
                ('font_size', models.CharField(max_length=8)),
                ('font_weight', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======

>>>>>>> dev2
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 5b4bdfc7f47bc7933ff73f8b9c316895d66d24e3
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('x', models.CharField(max_length=8)),
                ('y', models.CharField(max_length=8)),
                ('z', models.CharField(max_length=8)),
                ('width', models.CharField(max_length=8)),
                ('height', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.upload_to)),
=======
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribute')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.body')),
>>>>>>> 5b4bdfc7f47bc7933ff73f8b9c316895d66d24e3
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='TypeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribute')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.component')),
                ('html', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.html')),
=======
=======
>>>>>>> dev2
            name='SizeAndСoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=8)),
                ('y', models.CharField(max_length=8)),
                ('z', models.CharField(max_length=8)),
                ('width', models.CharField(max_length=8)),
                ('height', models.CharField(max_length=8)),
<<<<<<< HEAD
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typecomponent')),
=======
            ],
        ),
        migrations.CreateModel(

            name='TypeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),

>>>>>>> dev2
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.certificate')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.component')),
>>>>>>> 5b4bdfc7f47bc7933ff73f8b9c316895d66d24e3
            ],
        ),
        migrations.AddField(
            model_name='component',
<<<<<<< HEAD
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typecomponent'),
        ),
        migrations.CreateModel(
            name='CertificateLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.certificate')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.layout')),
            ],
=======
            name='size_and_coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sizeandсoordinates'),
>>>>>>> 5b4bdfc7f47bc7933ff73f8b9c316895d66d24e3
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='certificate',
            name='layouts',
<<<<<<< HEAD
            field=models.ManyToManyField(through='app.CertificateLayout', to='app.layout'),
=======
            field=models.ManyToManyField(through='app.Layout', to='app.Component'),
>>>>>>> 5b4bdfc7f47bc7933ff73f8b9c316895d66d24e3
        ),
=======
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typecomponent'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='component',
            field=models.ManyToManyField(through='app.Layout', to='app.component'),
        ),

>>>>>>> dev2
    ]
