# Generated by Django 3.2.16 on 2023-01-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='pdf/')),
                ('email', models.EmailField(max_length=254)),
                ('key', models.SlugField()),
            ],
        ),
    ]
