# Generated by Django 3.2.16 on 2022-11-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeandсoordinates',
            name='type',
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.typecomponent'),
        ),
    ]
