# Generated by Django 4.1.2 on 2022-10-25 04:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
