# Generated by Django 3.2.16 on 2022-11-03 10:18

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221102_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='component',
            name='body',
        ),
        migrations.RemoveField(
            model_name='component',
            name='size_and_coordinates',
        ),
        migrations.AddField(
            model_name='component',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='font',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='font_size',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='font_weight',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='height',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
        migrations.AddField(
            model_name='component',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='width',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='component',
            name='x',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='component',
            name='y',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='component',
            name='z',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typecomponent'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='SizeAndСoordinates',
        ),
    ]
