# Generated by Django 3.2.16 on 2023-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pdfcertificate_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcertificate',
            name='orientation',
            field=models.CharField(default='vertical', max_length=255),
        ),
    ]
