# Generated by Django 3.2.16 on 2022-11-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221103_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='component',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='component',
            name='height',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='component',
            name='width',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='component',
            name='x',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='component',
            name='y',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='component',
            name='z',
            field=models.CharField(max_length=8),
        ),
    ]
