# Generated by Django 3.2.16 on 2022-11-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221104_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='layout_key',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
