# Generated by Django 4.1.2 on 2022-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_layout_layout_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='z',
        ),
        migrations.AddField(
            model_name='component',
            name='opacity',
            field=models.CharField(blank=True, default='1', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='height',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='width',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
