# Generated by Django 4.1.2 on 2022-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_component_z_component_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='x',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='y',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
